// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:spoof_finny/models/experience_system.dart';
import 'package:spoof_finny/models/game_time_manager.dart';
import 'package:spoof_finny/models/money_system/credit_card.dart';
import 'package:spoof_finny/models/money_system/debit_card.dart';
import 'package:spoof_finny/models/money_system/money_manager.dart';
import 'package:spoof_finny/models/money_system/money_storage.dart';
import 'package:spoof_finny/models/money_system/saving_account.dart';
import 'package:spoof_finny/models/money_system/wallet.dart';
import 'package:spoof_finny/models/quests/quest.dart';
import 'package:spoof_finny/models/stats/stat_manager.dart';
import 'package:spoof_finny/models/user_info.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CreditCardAdapter());
    registerAdapter(DebitCardAdapter());
    registerAdapter(ExperienceSystemAdapter());
    registerAdapter(GameTimeManagerAdapter());
    registerAdapter(MoneyManagerAdapter());
    registerAdapter(MoneyStorageAdapter());
    registerAdapter(QuestAdapter());
    registerAdapter(SavingAccountAdapter());
    registerAdapter(StatManagerAdapter());
    registerAdapter(UserInfoAdapter());
    registerAdapter(WalletAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CreditCardAdapter());
    registerAdapter(DebitCardAdapter());
    registerAdapter(ExperienceSystemAdapter());
    registerAdapter(GameTimeManagerAdapter());
    registerAdapter(MoneyManagerAdapter());
    registerAdapter(MoneyStorageAdapter());
    registerAdapter(QuestAdapter());
    registerAdapter(SavingAccountAdapter());
    registerAdapter(StatManagerAdapter());
    registerAdapter(UserInfoAdapter());
    registerAdapter(WalletAdapter());
  }
}
