// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:spoof_finny/models/experience_system.dart';
import 'package:spoof_finny/models/game_events/change_stat_value_game_event.dart';
import 'package:spoof_finny/models/game_events/time_skipped.dart';
import 'package:spoof_finny/models/game_object.dart';
import 'package:spoof_finny/models/items/food.dart';
import 'package:spoof_finny/models/items/inventory.dart';
import 'package:spoof_finny/models/items/item.dart';
import 'package:spoof_finny/models/items/products_storage.dart';
import 'package:spoof_finny/models/money_system/credit_card.dart';
import 'package:spoof_finny/models/money_system/debit_card.dart';
import 'package:spoof_finny/models/money_system/money_manager.dart';
import 'package:spoof_finny/models/money_system/money_storage.dart';
import 'package:spoof_finny/models/money_system/saving_account.dart';
import 'package:spoof_finny/models/money_system/wallet.dart';
import 'package:spoof_finny/models/pet_sprites.dart';
import 'package:spoof_finny/models/quests/goals/buy_quest_goal.dart';
import 'package:spoof_finny/models/quests/goals/eat_quest_goal.dart';
import 'package:spoof_finny/models/quests/goals/exp_quest_goal.dart';
import 'package:spoof_finny/models/quests/goals/money_quest_goal.dart';
import 'package:spoof_finny/models/quests/goals/progress_goal.dart';
import 'package:spoof_finny/models/quests/goals/quest_goal.dart';
import 'package:spoof_finny/models/quests/goals/quest_goal_progress.dart';
import 'package:spoof_finny/models/quests/quest.dart';
import 'package:spoof_finny/models/quests/quest_manager.dart';
import 'package:spoof_finny/models/quests/quest_state.dart';
import 'package:spoof_finny/models/quests/rewards/experience_reward.dart';
import 'package:spoof_finny/models/quests/rewards/item_reward.dart';
import 'package:spoof_finny/models/quests/rewards/money_reward.dart';
import 'package:spoof_finny/models/quests/rewards/quest_reward.dart';
import 'package:spoof_finny/models/quests/rewards/stat_reward.dart';
import 'package:spoof_finny/models/quests/timed_quest.dart';
import 'package:spoof_finny/models/shop_system/shop.dart';
import 'package:spoof_finny/models/shop_system/shop_manager.dart';
import 'package:spoof_finny/models/shop_system/shop_product.dart';
import 'package:spoof_finny/models/stats/operator.dart';
import 'package:spoof_finny/models/stats/player_stat.dart';
import 'package:spoof_finny/models/stats/stat_manager.dart';
import 'package:spoof_finny/models/stats/stat_type.dart';
import 'package:spoof_finny/models/time_system/game_time.dart';
import 'package:spoof_finny/models/time_system/game_time_changed_event.dart';
import 'package:spoof_finny/models/time_system/game_time_manager.dart';
import 'package:spoof_finny/models/user_info.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BuyQuestGoalAdapter());
    registerAdapter(ChangeStatValueGameEventAdapter());
    registerAdapter(CreditCardAdapter());
    registerAdapter(DebitCardAdapter());
    registerAdapter(EatQuestGoalAdapter());
    registerAdapter(ExpQuestGoalAdapter());
    registerAdapter(ExperienceRewardAdapter());
    registerAdapter(ExperienceSystemAdapter());
    registerAdapter(FoodAdapter());
    registerAdapter(GameObjectAdapter());
    registerAdapter(GameTimeAdapter());
    registerAdapter(GameTimeChangedEventAdapter());
    registerAdapter(GameTimeManagerAdapter());
    registerAdapter(InventoryAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ItemRewardAdapter());
    registerAdapter(MoneyManagerAdapter());
    registerAdapter(MoneyQuestGoalAdapter());
    registerAdapter(MoneyRewardAdapter());
    registerAdapter(MoneyStorageAdapter());
    registerAdapter(OperatorAdapter());
    registerAdapter(PetSpritesAdapter());
    registerAdapter(PlayerStatAdapter());
    registerAdapter(ProductsStorageAdapter());
    registerAdapter(ProgressGoalAdapter());
    registerAdapter(QuestAdapter());
    registerAdapter(QuestGoalAdapter());
    registerAdapter(QuestGoalProgressAdapter());
    registerAdapter(QuestManagerAdapter());
    registerAdapter(QuestRewardAdapter());
    registerAdapter(QuestStateAdapter());
    registerAdapter(SavingAccountAdapter());
    registerAdapter(ShopAdapter());
    registerAdapter(ShopManagerAdapter());
    registerAdapter(ShopProductAdapter());
    registerAdapter(StatManagerAdapter());
    registerAdapter(StatRewardAdapter());
    registerAdapter(StatTypeAdapter());
    registerAdapter(TimeSkippedAdapter());
    registerAdapter(TimedQuestAdapter());
    registerAdapter(UserInfoAdapter());
    registerAdapter(WalletAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BuyQuestGoalAdapter());
    registerAdapter(ChangeStatValueGameEventAdapter());
    registerAdapter(CreditCardAdapter());
    registerAdapter(DebitCardAdapter());
    registerAdapter(EatQuestGoalAdapter());
    registerAdapter(ExpQuestGoalAdapter());
    registerAdapter(ExperienceRewardAdapter());
    registerAdapter(ExperienceSystemAdapter());
    registerAdapter(FoodAdapter());
    registerAdapter(GameObjectAdapter());
    registerAdapter(GameTimeAdapter());
    registerAdapter(GameTimeChangedEventAdapter());
    registerAdapter(GameTimeManagerAdapter());
    registerAdapter(InventoryAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ItemRewardAdapter());
    registerAdapter(MoneyManagerAdapter());
    registerAdapter(MoneyQuestGoalAdapter());
    registerAdapter(MoneyRewardAdapter());
    registerAdapter(MoneyStorageAdapter());
    registerAdapter(OperatorAdapter());
    registerAdapter(PetSpritesAdapter());
    registerAdapter(PlayerStatAdapter());
    registerAdapter(ProductsStorageAdapter());
    registerAdapter(ProgressGoalAdapter());
    registerAdapter(QuestAdapter());
    registerAdapter(QuestGoalAdapter());
    registerAdapter(QuestGoalProgressAdapter());
    registerAdapter(QuestManagerAdapter());
    registerAdapter(QuestRewardAdapter());
    registerAdapter(QuestStateAdapter());
    registerAdapter(SavingAccountAdapter());
    registerAdapter(ShopAdapter());
    registerAdapter(ShopManagerAdapter());
    registerAdapter(ShopProductAdapter());
    registerAdapter(StatManagerAdapter());
    registerAdapter(StatRewardAdapter());
    registerAdapter(StatTypeAdapter());
    registerAdapter(TimeSkippedAdapter());
    registerAdapter(TimedQuestAdapter());
    registerAdapter(UserInfoAdapter());
    registerAdapter(WalletAdapter());
  }
}
