name: spoof_finny
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flame: ^1.38.2
  flutter:
    sdk: flutter
  intl: ^0.20.3
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.12.0
  get_it: ^8.0.3
  hive_ce: ^2.20.0
  hive_ce_flutter: ^2.3.4
  json_serializer: ^0.3.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.1
  hive_ce_generator: ^1.11.3

flutter:
  uses-material-design: true
  assets:
    - assets/ # Добавляй здесь пути до папок с ассетами. Относительно папки spoof_finny
    - assets/images/
    - assets/images/hallway/
    - assets/images/kitchen/
    - assets/images/bathroom/
    - assets/images/bedroom/
    - assets/images/livingroom/

    - assets/images/player/kitty/child/green/
    - assets/images/player/kitty/teen/green/
    - assets/images/player/kitty/adult/green/
    - assets/images/player/kitty/child/grey/
    - assets/images/player/kitty/teen/grey/
    - assets/images/player/kitty/adult/grey/
    - assets/images/player/kitty/child/white/
    - assets/images/player/kitty/teen/white/
    - assets/images/player/kitty/adult/white/

    - assets/images/player/dog/child/blond/
    - assets/images/player/dog/teen/blond/
    - assets/images/player/dog/adult/blond/
    - assets/images/player/dog/child/brown/
    - assets/images/player/dog/teen/brown/
    - assets/images/player/dog/adult/brown/
    - assets/images/player/dog/child/white/
    - assets/images/player/dog/teen/white/
    - assets/images/player/dog/adult/white/

    - assets/images/food/
    - assets/images/food/fruits/
    - assets/images/food/desserts/
    - assets/images/food/drinks/
    - assets/images/food/main/
    - assets/images/food/second/
    - assets/images/food/vegetables/
    - assets/images/map/
